### ISSUE TITLE
For some players, it doesn't load everytime

### ISSUE THREAD

**Issue by MoravianLion** [JustAnotherModder/JAM_Drugs#3]
Hi,

works great for me, but we have noticed it doesn't always load for everyone. Right now, I am on the server, we wanted to go on raid together and I can enter and my friend can't. This is his console report

`Error resuming coroutine: @JAM/JAM_Drugs/JAM_Drugs_Client.lua:246: bad argument #1 to 'pairs' (table expected, got boolean)
[    825532] stack traceback:
[    825532] 	[C]: in function 'pairs'
[    825532] 	@JAM/JAM_Drugs/JAM_Drugs_Client.lua:246: in method 'SellDrugsToPed'
[    825547] 	@JAM/JAM_Drugs/JAM_Drugs_Client.lua:235: in method 'InputCheck'
[    825547] 	@JAM/JAM_Drugs/JAM_Drugs_Client.lua:28: in method 'ClientUpdate'
[    825547] 	@JAM/JAM_Drugs/JAM_Drugs_Client.lua:15: in method 'ClientStart'
[    825547] 	@JAM/JAM_Drugs/JAM_Drugs_Client.lua:861: in function <@JAM/JAM_Drugs/JAM_Drugs_Client.lua:861>`

This happened to me before too, but I though it's server side. It is definitely client's issue. No idea why though...

**Comment by JustAnotherModder** [comment]
Updated. Re-download. Thanks.
